const link = [
    "https://imag.malavida.com/mvimgbig/download-fs/dreams-of-desire-25123-0.jpg",                  
    "https://ih1.redbubble.net/image.778581959.7761/st,small,507x507-pad,600x600,f8f8f8.u11.jpg",   
    "https://i.pinimg.com/236x/db/c6/f9/dbc6f97fa21927334f3472b66bca182e.jpg",                      
    "https://static.f95zone.to/data/avatars/h/1773/1773363.jpg?1588198759",                         
    "https://img.itch.zone/aW1nLzI2NDA0MDkuanBn/315x250%23cm/wHjY0C.jpg",                           
    "https://apkmagic.com.ar/wp-content/uploads/2020/04/Lunars-Chosen-18-v0.9-Beta-2-MOD.jpeg",     
    "https://apkplusmod.com/logo/acting-lessons-mod-apk.jpg",                                       
    "https://steamcdn-a.akamaihd.net/steam/apps/1126320/header.jpg",                                
    "https://attachments.f95zone.to/2019/07/367944_AD.png",                                         
    "https://apkmagic.com.ar/wp-content/uploads/2020/04/Anna-Exciting-Affection-v1.6-MOD-18.jpeg",  
    "https://pbs.twimg.com/media/EZb2QfIXYAgPh5L.png",                                              
    "https://attachments.f95zone.to/2019/11/478352_Connected_2019-11-18_23-44-28-517.jpg",          
    "https://apkmagic.com.ar/wp-content/uploads/2020/06/A-Mothers-Love-vPart-7MOD-18.jpeg",         
    "https://img.itch.zone/aW1nLzIwNjk2MDAucG5n/original/JZhLMr.png",                               
    "https://i.imgur.com/UuXRnLY.jpg",                                                              
    "https://attachments.f95zone.com/2018/11/198104_3gndoor03.jpg",                                 
    "https://i.imgur.com/fVuAdkW.jpg",                                                              
    "https://apkmagic.com.ar/wp-content/uploads/2019/09/1567438016_868_Betrayed-18-v0.4.5-MOD.jpeg",
    "https://attachments.f95zone.to/2018/08/147944_PORTADA_JOC_FINAL_v8_PER_F95ZONE.png",           
    "https://attachments.f95zone.to/2019/04/288157_bm_cover.jpg",                                   
    "https://img.itch.zone/aW1hZ2UvNDA1ODA3LzIwMTQ0MDYucG5n/original/8KLBvD.png",                   
    "https://pp.userapi.com/c854020/v854020130/70b2e/MNj8TQMrpPE.jpg",                              
    "https://apklord.com/logos/Dating-My-Daughter.jpg",                                             
    "https://i1.wp.com/love-joint.com/blog/wp-content/uploads/2020/08/Epi17.png?fit=760%2C428",     
    "https://platinmods.com/attachments/e29a9db71714c343a2f841e7fad051c4-jpg-jpg.186924/",          
    "https://img.itch.zone/aW1nLzI2MzM5NjYucG5n/original/D9QD0Y.png",                               
    "https://picon.ngfiles.com/738000/flash_738057_largest_crop.jpg?f1568056923",
    "https://2.bp.blogspot.com/-xMpRqj4dM5w/WxQtFZbRXuI/AAAAAAAAADQ/fASbVbYJkK0mLHmpn9khUrnRCpXHriFggCLcBGAs/w1200-h630-p-k-no-nu/82211_G3fcCxGjzlNmOxv19I-8JSLYggFJdYbAcjnDEmw97zEXNwO3GZ79mvpTxo_LK5aD.png",              
    "https://c10.patreonusercontent.com/3/eyJ3IjoxOTIwfQ%3D%3D/patreon-media/p/campaign/3130967/9fcd64db13ea46f185c5d61253627220/4.png?token-time=1599177600&amp;token-hash=Ul2Q0B-yYHgrAgzHouwdaq4m7DrCzvmSO-bbuQSpVJI%3D",
    "https://preview.redd.it/92xkqzbe2ey41.jpg?width=829&amp;format=pjpg&amp;auto=webp&amp;s=4e019f675084d661dd6811fb627acfbf7d1d3317",                                                                                     
    "https://apkwarehouse.org/wp-content/uploads/2018/08/dreams-of-desire-the-lost-memories-apk-apkwarehouse.org-7-300x275.jpg",                                                                                            
    "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS8xQcnaYRVCzY9oUI78SusmHF8Gkh9buSdLw&usqp=CAU",                                                                                                                                   
]
const path = [
    "https://f95zone.to/threads/dreams-of-desire-v1-0-3-lewdlab.1904/",                                 
    "https://f95zone.to/threads/amnesia-v0-2c-super-alex.44511/",                                       
    "https://f95zone.to/threads/milfy-city-v0-6e-icstor.8012/",                                         
    "https://f95zone.to/threads/savior-v0-4c-purple-fellas.40217/",                                     
    "https://f95zone.to/threads/tales-from-the-unending-void-v0-4-extra-perverteer.42668/",             
    "https://f95zone.to/threads/lunars-chosen-v0-10-1-patreon-ptgames.28364/",                          
    "https://f95zone.to/threads/acting-lessons-v1-0-2-drpinkcake.12181/",                               
    "https://f95zone.to/threads/being-a-dik-v0-5-2-dr-pinkcake.25332/",                                 
    "https://f95zone.to/threads/altered-destiny-v0-02b-iccreations.46615/",                             
    "https://f95zone.to/threads/anna-exciting-affection-unofficial-renpy-remake-v2-0-osmcuser132.8482/",
    "https://f95zone.to/threads/treasure-of-nadia-v44081-nlt-media.38582/",                             
    "https://f95zone.to/threads/connected-v0-2-5-chainzero.40614/",                                     
    "https://f95zone.to/threads/a-mothers-love-part-1-8-plus-orborigin.25146/",                         
    "https://f95zone.to/threads/away-from-home-ep-1-9-vatosgames.29666/",                               
    "https://f95zone.to/threads/babysitters-v0-0-4b-t4bbo.30446/",                                      
    "https://f95zone.to/threads/become-a-rock-star-v0-60-mr-jet.17836/",                                
    "https://f95zone.to/threads/behind-the-walls-s01e03-test-lstudio.22720/",                           
    "https://f95zone.to/threads/betrayed-v0-62-joraell.17512/",                                         
    "https://f95zone.to/threads/big-citys-pleasures-v0-2-4c-porcus.16290/",                             
    "https://f95zone.to/threads/bad-memories-v0-5-2-recreation.28008/",                                 
    "https://f95zone.to/threads/c-plan-v0-0-3a-lovemilfs.28762/",                                       
    "https://f95zone.to/threads/come-inside-v0-2-1-ttll.32087/",                                        
    "https://f95zone.to/threads/dating-my-daughter-ch-1-3-v0-27-mrdots-games.597/",                     
    "https://f95zone.to/threads/double-homework-ep-12-palmer.28238/",                                   
    "https://f95zone.to/threads/echoes-of-lust-s2e1-inceton.21005/",                                    
    "https://f95zone.to/threads/false-hero-v0-25-beta-enyo-eerie.14204/",                               
    "https://f95zone.to/threads/midnight-paradise-v0-10-lewdlab.25081/",                                
    "https://f95zone.to/threads/f-i-l-f-v0-11c-iccreations.9605/",                   
    "https://f95zone.to/threads/deliverance-ch-9-1thousand.36263/",                  
    "https://f95zone.to/threads/big-brother-fan-game-v0-13-fix-7-porngodnoob.19709/",
    "https://f95zone.to/threads/dreams-of-desire-the-lost-memories-lewdlab.15060/",  
    "https://store.steampowered.com/app/1358250/City_of_Broken_Dreamers_Book_One/",  
]
const name = [
    "Dreams of Desire",                
    "Amnesia",                         
    "Milfy City",                      
    "Savior",                          
    "Tales from the Unending Void",    
    "Lunars Chosen",                   
    "Acting Lessons",                  
    "Being a DIK",                     
    "Altered destiny",                 
    "Anna exciting affection [Ren'py]",
    "Treasure of Nadia",               
    "Connected",                       
    "a mothers love",                  
    "Away from Home",                  
    "Babysitters",                     
    "Become a Rockstar",               
    "Behind the Walls",                
    "Betrayed",                        
    "Big city's Pleasures",            
    "Bad memories",                    
    "C-Plan",                          
    "Come inside",                     
    "Dating my Daughter",              
    "Double Homework",                 
    "Echoes of Lust",                  
    "False Hero",                      
    "Midnight Paradise",               
    "F.I.L.F",                            
    "Devilerance",                        
    "Big Brother [Ren'py]",               
    "Dreams of Desire: The Lost Memories",
    "City of Broken Dreamers: Book One",  
]
const version = [
    "1.0.3 Completed",
    "v0.2c",          
    "v0.6e",          
    "v0.4c",          
    "v0.4",           
    "v0.10.1",        
    "v1.0.2 Completed",
    "v0.5.2",         
    "v0.02a",         
    "v2.0",           
    "v44.081",        
    "v0.2",           
    "part 7",         
    "ep 9",           
    "v0.0.4",         
    "v0.60",          
    "s01 e03",        
    "v0.61",          
    "v0.2.2",         
    "v0.5",           
    "v0.0.3a",        
    "v0.2.1",         
    "ch 3 v0.27",     
    "ep 17",          
    "s02 e01",        
    "v0.25",          
    "v0.10",          
    "v0.11c",
    "ch. 9",
    "v0.13",
    "Completed",
    "Completed",
]
setLocalStorageItems = () => {
    let r = confirm("Are you sure? All unsaved changes will be lost!");
    if (r == true) {
        localStorage.setItem("LSlink", JSON.stringify(link))
        localStorage.setItem("LSpath", JSON.stringify(path))
        localStorage.setItem("LSname", JSON.stringify(name))
        localStorage.setItem("LSversion", JSON.stringify(version))
        console.log("LocalStorage Items successfully set!")
    }
}

allGames = () => {
    for (i = 0; i < JSON.parse(localStorage.getItem("LSname")).length; i++){
        gameContainer(
            JSON.parse(localStorage.getItem("LSlink"))[i],
            JSON.parse(localStorage.getItem("LSpath"))[i],
            JSON.parse(localStorage.getItem("LSname"))[i],
            JSON.parse(localStorage.getItem("LSversion"))[i]
        )
    }
}



